# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UiForm/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(968, 672)
        MainWindow.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./UiForm/../../icons/python.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 200, 551))
        self.treeWidget.setMouseTracking(False)
        self.treeWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.treeWidget.setLineWidth(3)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 0, 771, 551))
        self.label.setMouseTracking(True)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(3)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setGeometry(QtCore.QRect(200, 0, 771, 551))
        self.scrollArea.setMouseTracking(True)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setLineWidth(3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 759, 539))
        self.scrollAreaWidgetContents.setMouseTracking(True)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_Plus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Plus.setGeometry(QtCore.QRect(215, 15, 25, 25))
        self.pushButton_Plus.setMouseTracking(True)
        self.pushButton_Plus.setTabletTracking(False)
        self.pushButton_Plus.setObjectName("pushButton_Plus")
        self.pushButton_Minus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Minus.setGeometry(QtCore.QRect(245, 15, 25, 25))
        self.pushButton_Minus.setMouseTracking(True)
        self.pushButton_Minus.setObjectName("pushButton_Minus")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 571, 972, 60))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setLineWidth(3)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 2, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(320)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(70)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 552, 971, 15))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./UiForm/../../icons/hide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 968, 22))
        self.menubar.setMouseTracking(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setMouseTracking(False)
        self.menuFile.setStatusTip("")
        self.menuFile.setObjectName("menuFile")
        self.menuFilter = QtWidgets.QMenu(self.menubar)
        self.menuFilter.setEnabled(True)
        self.menuFilter.setObjectName("menuFilter")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMouseTracking(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Image = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./UiForm/../../icons/blue-folder-horizontal-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_Image.setIcon(icon2)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionRemove_Image = QtWidgets.QAction(MainWindow)
        self.actionRemove_Image.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./UiForm/../../icons/cross-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_Image.setIcon(icon3)
        self.actionRemove_Image.setObjectName("actionRemove_Image")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./UiForm/../../icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon4)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_Group = QtWidgets.QAction(MainWindow)
        self.actionSave_Group.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./UiForm/../../icons/disk--pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Group.setIcon(icon5)
        self.actionSave_Group.setObjectName("actionSave_Group")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./UiForm/../../icons/if_logout_48698.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon6)
        self.actionExit.setObjectName("actionExit")
        self.actionEdges = QtWidgets.QAction(MainWindow)
        self.actionEdges.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("./UiForm/../../icons/application-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdges.setIcon(icon7)
        self.actionEdges.setObjectName("actionEdges")
        self.actionGaussian = QtWidgets.QAction(MainWindow)
        self.actionGaussian.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("./UiForm/../../icons/icon-diagram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGaussian.setIcon(icon8)
        self.actionGaussian.setObjectName("actionGaussian")
        self.actionThreshold = QtWidgets.QAction(MainWindow)
        self.actionThreshold.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("./UiForm/../../icons/scissors.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionThreshold.setIcon(icon9)
        self.actionThreshold.setObjectName("actionThreshold")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("./UiForm/../../icons/question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon10)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout_the_Authors = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("./UiForm/../../icons/if_hire-me_48687.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_the_Authors.setIcon(icon11)
        self.actionAbout_the_Authors.setObjectName("actionAbout_the_Authors")
        self.actionAbout_the_App = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("./UiForm/../../icons/if_special-offer_48729.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_the_App.setIcon(icon12)
        self.actionAbout_the_App.setObjectName("actionAbout_the_App")
        self.actionOrientation = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("./UiForm/../../icons/clipboard-paste-document-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOrientation.setIcon(icon13)
        self.actionOrientation.setObjectName("actionOrientation")
        self.actionReport = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("./UiForm/../../icons/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReport.setIcon(icon14)
        self.actionReport.setObjectName("actionReport")
        self.actionasdasd = QtWidgets.QAction(MainWindow)
        self.actionasdasd.setObjectName("actionasdasd")
        self.menuFile.addAction(self.actionLoad_Image)
        self.menuFile.addAction(self.actionRemove_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_Group)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuFilter.addAction(self.actionEdges)
        self.menuFilter.addAction(self.actionGaussian)
        self.menuFilter.addAction(self.actionThreshold)
        self.menuOptions.addAction(self.actionHelp)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionOrientation)
        self.menuOptions.addAction(self.actionReport)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionAbout_the_Authors)
        self.menuOptions.addAction(self.actionAbout_the_App)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Malik Images"))
        self.pushButton_Plus.setStatusTip(_translate("MainWindow", "Enlarge the image"))
        self.pushButton_Plus.setText(_translate("MainWindow", "+"))
        self.pushButton_Minus.setStatusTip(_translate("MainWindow", "Shrink the image"))
        self.pushButton_Minus.setText(_translate("MainWindow", "-"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "RMSE"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PSNR"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SNR"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setShortcut(_translate("MainWindow", "Esc"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuFilter.setTitle(_translate("MainWindow", "Fil&ters"))
        self.menuOptions.setTitle(_translate("MainWindow", "O&ptions"))
        self.actionLoad_Image.setText(_translate("MainWindow", "Load Image"))
        self.actionLoad_Image.setIconText(_translate("MainWindow", "Load Image"))
        self.actionLoad_Image.setStatusTip(_translate("MainWindow", "Load a new image"))
        self.actionLoad_Image.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionRemove_Image.setText(_translate("MainWindow", "Remove Image"))
        self.actionRemove_Image.setIconText(_translate("MainWindow", "Remove Image"))
        self.actionRemove_Image.setStatusTip(_translate("MainWindow", "Remove a image"))
        self.actionRemove_Image.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionSave.setText(_translate("MainWindow", "Save Image"))
        self.actionSave.setIconText(_translate("MainWindow", "Save Image"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save a selected image"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_Group.setText(_translate("MainWindow", "Save Images in Group"))
        self.actionSave_Group.setIconText(_translate("MainWindow", "Save Images in Group"))
        self.actionSave_Group.setStatusTip(_translate("MainWindow", "Save a image and his images derivation"))
        self.actionSave_Group.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Close the program"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+F4"))
        self.actionEdges.setText(_translate("MainWindow", "Edges"))
        self.actionEdges.setStatusTip(_translate("MainWindow", "Edge filters "))
        self.actionEdges.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionGaussian.setText(_translate("MainWindow", "Gaussian"))
        self.actionGaussian.setStatusTip(_translate("MainWindow", "Gaussian filters"))
        self.actionGaussian.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionThreshold.setText(_translate("MainWindow", "Threshold"))
        self.actionThreshold.setStatusTip(_translate("MainWindow", "Threshold filters"))
        self.actionThreshold.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setStatusTip(_translate("MainWindow", "Show program help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1"))
        self.actionAbout_the_Authors.setText(_translate("MainWindow", "About the Authors"))
        self.actionAbout_the_Authors.setShortcut(_translate("MainWindow", "F10"))
        self.actionAbout_the_App.setText(_translate("MainWindow", "About the App"))
        self.actionAbout_the_App.setShortcut(_translate("MainWindow", "F11"))
        self.actionOrientation.setText(_translate("MainWindow", "Orientation"))
        self.actionOrientation.setShortcut(_translate("MainWindow", "F6"))
        self.actionReport.setText(_translate("MainWindow", "Report"))
        self.actionReport.setShortcut(_translate("MainWindow", "F7"))
        self.actionasdasd.setText(_translate("MainWindow", "asdasd"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
