# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UiForm/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./UiForm/../demo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 200, 556))
        self.treeWidget.setMouseTracking(True)
        self.treeWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.treeWidget.setLineWidth(3)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 0, 600, 556))
        self.label.setMouseTracking(True)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(3)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setGeometry(QtCore.QRect(200, 0, 600, 556))
        self.scrollArea.setMouseTracking(True)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setLineWidth(3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 588, 544))
        self.scrollAreaWidgetContents.setMouseTracking(True)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_Plus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Plus.setGeometry(QtCore.QRect(215, 15, 25, 25))
        self.pushButton_Plus.setMouseTracking(True)
        self.pushButton_Plus.setTabletTracking(False)
        self.pushButton_Plus.setObjectName("pushButton_Plus")
        self.pushButton_Minus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Minus.setGeometry(QtCore.QRect(245, 15, 25, 25))
        self.pushButton_Minus.setMouseTracking(True)
        self.pushButton_Minus.setObjectName("pushButton_Minus")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuFilter = QtWidgets.QMenu(self.menubar)
        self.menuFilter.setEnabled(True)
        self.menuFilter.setObjectName("menuFilter")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMouseTracking(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Image = QtWidgets.QAction(MainWindow)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionRemove_Image = QtWidgets.QAction(MainWindow)
        self.actionRemove_Image.setEnabled(False)
        self.actionRemove_Image.setObjectName("actionRemove_Image")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_Group = QtWidgets.QAction(MainWindow)
        self.actionSave_Group.setEnabled(False)
        self.actionSave_Group.setObjectName("actionSave_Group")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionEdges = QtWidgets.QAction(MainWindow)
        self.actionEdges.setEnabled(False)
        self.actionEdges.setObjectName("actionEdges")
        self.actionGaussian = QtWidgets.QAction(MainWindow)
        self.actionGaussian.setEnabled(False)
        self.actionGaussian.setObjectName("actionGaussian")
        self.actionThreshold = QtWidgets.QAction(MainWindow)
        self.actionThreshold.setEnabled(False)
        self.actionThreshold.setObjectName("actionThreshold")
        self.menuFile.addAction(self.actionLoad_Image)
        self.menuFile.addAction(self.actionRemove_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_Group)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuFilter.addAction(self.actionEdges)
        self.menuFilter.addAction(self.actionGaussian)
        self.menuFilter.addAction(self.actionThreshold)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Plus.setText(_translate("MainWindow", "+"))
        self.pushButton_Minus.setText(_translate("MainWindow", "-"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuFilter.setTitle(_translate("MainWindow", "Filter"))
        self.actionLoad_Image.setText(_translate("MainWindow", "Load"))
        self.actionRemove_Image.setText(_translate("MainWindow", "Remove"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_Group.setText(_translate("MainWindow", "Save Group"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionEdges.setText(_translate("MainWindow", "Edges"))
        self.actionGaussian.setText(_translate("MainWindow", "Gaussian"))
        self.actionThreshold.setText(_translate("MainWindow", "Threshold"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
